sudo: false

language: go
go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - master

env:
  global:
    - DEP_VERSION="0.4.1"
    - DEP_SHA=31144e465e52ffbc0035248a10ddea61a09bf28b00784fd3fdd9882c8cbb2315

matrix:
  allow_failures:
    - go: master

before_install:
  - curl -fL -o $GOPATH/bin/dep https://github.com/golang/dep/releases/download/v$DEP_VERSION/dep-linux-amd64  && echo "$DEP_SHA $GOPATH/bin/dep" | sha256sum -c - && chmod +x $GOPATH/bin/dep

install:
  - go get -u github.com/golang/lint/golint
  - dep ensure

script:
  - bash rungas.sh
  - grep -L -r --include *.go --exclude-dir vendor -P "Copyright (\d{4}|\(c\)) Microsoft" ./ | tee /dev/stderr | test -z "$(< /dev/stdin)"
  - go build $(go list ./... | grep -v vendor)
  - test -z "$(go fmt $(go list ./... | grep -v vendor) | tee /dev/stderr)"
  - go vet $(go list ./... | grep -v vendor)
  - go test $(sh ./findTestedPackages.sh)
